<?php

namespace AppBundle\Repository;

/**
 * ContenuDepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenuDepotRepository extends \Doctrine\ORM\EntityRepository
{
    
     public function getAll()
    {
        return $this->getEntityManager()
                ->createQuery(
                'SELECT c FROM AppBundle:Contenu c')
                ->getResult();
    }
}
