<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * ConteneurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConteneurRepository extends \Doctrine\ORM\EntityRepository
{
     public function add($conteneur) {
         $conteneur->setNiveau(0);
         $this->getEntityManager()->persist($conteneur);
         $this->getEntityManager()->flush();
    }
    
    public function getAlmostFull($idParc)
    {
        $entityManager = $this->getEntityManager();
        $rsm = new \Doctrine\ORM\Query\ResultSetMappingBuilder($entityManager);
        $rsm->addRootEntityFromClassMetadata('AppBundle:Conteneur', 'c');
        $rsm->addJoinedEntityFromClassMetadata('AppBundle:Dechet', 'd', 'c', 'dechets', array('id' => 'id_dechet'));
        $sqlQuery ="SELECT * FROM `conteneur` c "
                ."JOIN dechet d on c.id_dechet = d.id "
                . "WHERE c.niveau/c.contenance >= ? AND etat <> ? AND c.id_parc =?";
       
        $query = $entityManager->createNativeQuery($sqlQuery,$rsm);
        $query->setParameter(1, 0.8);
        $query->setParameter(2, 1);
        $query->setParameter(3, $idParc);
        $result = $query->getResult();
        return $result;
    }
    
    public function getParcConteneurs($idParc)
    {
        $entityManager = $this->getEntityManager();
        $rsm = new \Doctrine\ORM\Query\ResultSetMappingBuilder($entityManager);
        $rsm->addRootEntityFromClassMetadata('AppBundle:Conteneur', 'c');
        $rsm->addJoinedEntityFromClassMetadata('AppBundle:Dechet', 'd', 'c', 'dechets', array('id' => 'id_dechet'));
        $sqlQuery ="SELECT * FROM `conteneur` c "
                ."JOIN dechet d on c.id_dechet = d.id "
                . "WHERE c.etat <> ? AND c.id_parc =?";
       
        $query = $entityManager->createNativeQuery($sqlQuery,$rsm);
        $query->setParameter(1, 1);
        $query->setParameter(2, $idParc);
        $result = $query->getResult();
        return $result;
    }
    
    
    public function findAllWithRelatedEntities()
    {
        $query = $this->getEntityManager()
        ->createQuery(
        'SELECT p, c, d FROM AppBundle:Parc c
        JOIN p.conteneurs c 
        JOIN c.dechets d');
        try{
            return $query->getResult();
        } catch (Exception $ex) {
            return null;
        }
         
    }
    
    public function cloturer($id)
    {
        $query = $this->getEntityManager()->getConnection()->prepare("UPDATE conteneur set etat = 1 WHERE id_dechet= :id"); 
        $query->bindValue('id', $id);
        $query->execute();
        
    }
}
