<?php

namespace AppBundle\Repository;

/**
 * DepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepotRepository extends \Doctrine\ORM\EntityRepository
{
    public function add($depot) {
        $depot->setDate(new \DateTime('now'));
        $this->getEntityManager()->persist($depot);
        $this->getEntityManager()->flush();
        
    }
    
    
}
