<?php

namespace AppBundle\Repository;

/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends \Doctrine\ORM\EntityRepository {

    public function add($facture) {
        $this->getEntityManager()->persist($facture);
        $this->getEntityManager()->flush();
    }

    public function getByMenage($id) {
        $query = $this->getEntityManager()
                ->createQuery(
                'SELECT f, m,mn, d FROM AppBundle:Facture f
        JOIN f.montantsDetailles m
        JOIN f.menage mn
        JOIN m.dechet d 
        WHERE mn.id = ?1');
        $query->setParameter(1, $id);
        try {
            return $query->getResult();
        } catch (Exception $ex) {
            return null;
        }
    }
    
    public function getDetails($id) {
        $query = $this->getEntityManager()
                ->createQuery(
                'SELECT m, d, f FROM AppBundle:MontantDetaille m
        JOIN m.dechet d 
        JOIN m.facture f
        WHERE f.id = ?1');
        $query->setParameter(1, $id);
        try {
            return $query->getResult();
        } catch (Exception $ex) {
            return null;
        }
    }

}
