<?php

namespace AppBundle\Repository;

/**
 * MontantDetailleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MontantDetailleRepository extends \Doctrine\ORM\EntityRepository
{
}
